Script started on Mon Feb  2 15:39:21 2015
[01;32mElvis@ucrwpa1-2-132-174[00m:[01;36m~/Documents/UCR /CS 100/rshell/tests[00m$ cd ..
[01;32mElvis@ucrwpa1-2-132-174[00m:[01;36m~/Documents/UCR /CS 100/rshell[00m$ vi[K[Kbin/rshell 
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls -a
[36m.[m[m         .DS_Store LICENSE   README.md [36mobj[m[m       test
[36m..[m[m        [36m.git[m[m      Makefile  [36mbin[m[m       [36msrc[m[m       [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls -a -l  
total 88
drwxr-xr-x  12 Elvis  staff    408 Feb  2 15:38 [36m.[m[m
drwxr-xr-x  11 Elvis  staff    374 Jan 30 16:00 [36m..[m[m
-rw-r--r--@  1 Elvis  staff   8196 Feb  2 15:39 .DS_Store
drwxr-xr-x  13 Elvis  staff    442 Feb  2 05:12 [36m.git[m[m
-rw-r--r--   1 Elvis  staff  18027 Jan 30 16:00 LICENSE
-rw-r--r--   1 Elvis  staff    339 Jan 30 16:00 Makefile
-rw-r--r--   1 Elvis  staff    236 Jan 30 16:00 README.md
drwxr-xr-x   3 Elvis  staff    102 Feb  2 15:38 [36mbin[m[m
drwxr-xr-x   5 Elvis  staff    170 Feb  2 15:39 [36mobj[m[m
drwxr-xr-x   6 Elvis  staff    204 Jan 30 16:20 [36msrc[m[m
-rw-r--r--   1 Elvis  staff    758 Jan 30 16:00 test
drwxr-xr-x   4 Elvis  staff    136 Jan 30 16:01 [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
error in execvp: File name too long
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls sdadafafdsgdbfaretsrhgfsdasghdfdsfagshfdtaresrhdgfnd f ad sdgsfsdgsgsd fgsb ffgfdhbdgsags
ls: ad: No such file or directory
ls: f: No such file or directory
ls: ffgfdhbdgsags: No such file or directory
ls: fgsb: No such file or directory
ls: sdadafafdsgdbfaretsrhgfsdasghdfdsfagshfdtaresrhdgfnd: No such file or directory
ls: sdgsfsdgsgsd: No such file or directory
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ 	
error in execvp: No such file or directory
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls #sdfasd
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ;
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ;;&&||
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls && ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls;ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ false && ls
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls || ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ pwd
/Users/Elvis/Documents/UCR /CS 100/rshell
[rshell]Elvis@ucrwpa1-2-132-174.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ exit
[01;32mElvis@ucrwpa1-2-132-174[00m:[01;36m~/Documents/UCR /CS 100/rshell[00m$ exit
exit

Script done on Mon Feb  2 15:44:32 2015
