Script started on Fri Jan 30 14:43:57 2015
[01;32mElvis@ucrwpa2-2-172-230[00m:[01;36m~/Documents/UCR /CS 100/rshell/tests[00m$ cd ..
[01;32mElvis@ucrwpa2-2-172-230[00m:[01;36m~/Documents/UCR /CS 100/rshell[00m$ bin/rshell
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ -a
error in execvp: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls -a
[36m.[m[m         .DS_Store LICENSE   README.md [36mobj[m[m       test
[36m..[m[m        [36m.git[m[m      Makefile  [36mbin[m[m       [36msrc[m[m       [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls -    s -a -l
error in execvp: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls    -l -a
total 80
drwxr-xr-x  12 Elvis  staff    408 Jan 30 14:42 [36m.[m[m
drwxr-xr-x  11 Elvis  staff    374 Jan 30 14:25 [36m..[m[m
-rw-r--r--@  1 Elvis  staff   6148 Jan 30 14:44 .DS_Store
drwxr-xr-x  14 Elvis  staff    476 Jan 30 14:31 [36m.git[m[m
-rw-r--r--   1 Elvis  staff  18027 Jan 30 14:25 LICENSE
-rw-r--r--   1 Elvis  staff    339 Jan 30 14:25 Makefile
-rw-r--r--   1 Elvis  staff    236 Jan 30 14:25 README.md
drwxr-xr-x   4 Elvis  staff    136 Jan 30 14:43 [36mbin[m[m
drwxr-xr-x   4 Elvis  staff    136 Jan 30 14:43 [36mobj[m[m
drwxr-xr-x   5 Elvis  staff    170 Jan 30 14:30 [36msrc[m[m
-rw-r--r--   1 Elvis  staff    758 Jan 30 14:24 test
drwxr-xr-x   3 Elvis  staff    102 Jan 30 14:43 [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls  -l
total 64
-rw-r--r--  1 Elvis  staff  18027 Jan 30 14:25 LICENSE
-rw-r--r--  1 Elvis  staff    339 Jan 30 14:25 Makefile
-rw-r--r--  1 Elvis  staff    236 Jan 30 14:25 README.md
drwxr-xr-x  4 Elvis  staff    136 Jan 30 14:43 [36mbin[m[m
drwxr-xr-x  4 Elvis  staff    136 Jan 30 14:43 [36mobj[m[m
drwxr-xr-x  5 Elvis  staff    170 Jan 30 14:30 [36msrc[m[m
-rw-r--r--  1 Elvis  staff    758 Jan 30 14:24 test
drwxr-xr-x  3 Elvis  staff    102 Jan 30 14:43 [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls  -r
[36mtests[m[m     test      [36msrc[m[m       [36mobj[m[m       [36mbin[m[m       README.md Makefile  LICENSE
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls  -
ls: -: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ asdfasdfdsfasdfasdfasfasdfasdassfadsfsdafasdfsadfads
error in execvp: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls  ls ls ls ls ls
ls: ls: No such file or directory
ls: ls: No such file or directory
ls: ls: No such file or directory
ls: ls: No such file or directory
ls: ls: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls ls
ls: ls: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls ls ls ls
ls: ls: No such file or directory
ls: ls: No such file or directory
ls: ls: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ a -l ls
error in execvp: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ asd sad ls
error in execvp: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls #asd
ls: fts_open: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$   ls  #asd
ls: fts_open: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls 
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls 
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ pwd
/Users/Elvis/Documents/UCR /CS 100/rshell
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ pwd  #dasd
usage: pwd [-L | -P]
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ^[[A    #asd
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ #qwer
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls #l
ls: fts_open: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ 
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls #asd
ls: fts_open: No such file or directory
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ exit
0
[01;32mElvis@ucrwpa2-2-172-230[00m:[01;36m~/Documents/UCR /CS 100/rshell[00m$ make
g++ -ansi -pedantic -Wall -Werror -c -o obj/rshell.o src/rshell.cpp
g++ -o bin/rshell obj/rshell.o obj/type_prompt.o
[01;32mElvis@ucrwpa2-2-172-230[00m:[01;36m~/Documents/UCR /CS 100/rshell[00m$ bin/rshell 
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ la s #asd
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ ls #aqwe
LICENSE   Makefile  README.md [36mbin[m[m       [36mobj[m[m       [36msrc[m[m       test      [36mtests[m[m
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ pwd #ldsa
/Users/Elvis/Documents/UCR /CS 100/rshell
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ #asd
[rshell]Elvis@ucrwpa2-2-172-230.bulk.ucr.edu:~/Documents/UCR /CS 100/rshell$ exit
0


Script done on Fri Jan 30 14:50:03 2015
